# Lab3: NumPy1

**[실습 유의 사항]**

https://docs.google.com/spreadsheets/d/1LufpYknSbN7179sVPreZ-hDJ7vHaZ1l64XMZeivjySQ/edit?usp=sharing

공유한 파일에 실습 현황을 공유해 주세요. 수업 진행에 도움이 됩니다.

**문제1-1 Why NumPy?**

100*100 크기의 2차원 Matrix를 Python built-in list와 NumPy ndarray로 각각 만들어보세요.

Matrix의 내용은 python의 random 모듈과 numpy의 random을 각각 이용하여 채우시면 됩니다.


In [13]:
import numpy as np
import random

nparr = np.random.random((100, 100))
pyarr = [[random.random() for _ in range(10)] for _ in range(10)]

print(pyarr)
#print(np.ndarray(a))

[[0.6299745516293105, 0.06145886433253711, 0.11024445300878039, 0.8646686969388632, 0.1281300135059853, 0.34876111581795766, 0.6926851378321304, 0.5835839072408026, 0.36617040452603866, 0.1329342083620616], [0.5460183847786927, 0.8879760480412279, 0.0604347584054894, 0.9054548394344839, 0.5563726902857945, 0.554925352542266, 0.027746871797763917, 0.044486828055159244, 0.14262910252409422, 0.0988998622166074], [0.9295252222192542, 0.7767707468999204, 0.15257910216434067, 0.7765290075376913, 0.602568722627686, 0.7623209072254533, 0.5578568837371669, 0.5810140766446783, 0.7364081465585968, 0.2592363656386527], [0.8677024699175679, 0.5619530265675596, 0.8709672136042367, 0.4154399908644497, 0.26839223979535876, 0.9283011424543487, 0.4402257522709937, 0.9695794234290105, 0.08426319090802381, 0.8027565859282371], [0.9912668838896352, 0.28728516877281074, 0.13325076360844834, 0.000878432153969988, 0.9732800198565241, 0.8031058889324982, 0.2701433315331869, 0.6457948986686513, 0.74529989558729

---

**문제1-2 Why NumPy?**   
문제 1에서 만든 두 Matrix 각각이 자기 자신과 곱한 결과를 구해보세요

Python built-it list: A

NumPy ndarray: B

라고 했을 때, A\*A와 B\*B를 구하시면 됩니다.

In [23]:
import numpy as np
import random

nparr = np.random.random((100, 100))
# print(nparr)
pyarr = [[random.random() for _ in range(100)] for _ in range(100)]

print(nparr*nparr)

# [[] for in range]
# 다른 array도 생각해보자..
newarr = []
for i, l in enumerate(pyarr):
    newarr.append([x*pyarr[i][j] for j, x in enumerate(l)])
print(len(newarr))



[[0.150461   0.10388086 0.71843049 ... 0.51748088 0.01460078 0.15064494]
 [0.0105677  0.16530334 0.01907418 ... 0.0011371  0.0404932  0.01737622]
 [0.40528749 0.37737866 0.35376675 ... 0.20395467 0.54633951 0.12489786]
 ...
 [0.11773918 0.78376797 0.62069492 ... 0.01832781 0.51803901 0.02639034]
 [0.5090138  0.16265462 0.76669272 ... 0.41782632 0.14886123 0.17518982]
 [0.00222632 0.53616341 0.39101785 ... 0.58488046 0.09833362 0.28832485]]
100


---

**문제1-3 Why NumPy?**  
time 모듈의 time 함수를 이용해서 각 계산에 소요되는 시간을 측정해보세요.

예시)
time 함수는 다음과 같이 사용하면 됩니다.

```
>>> import time
>>> start = time.time()
>>> #------------------
>>> #계산 코드
>>> #------------------
>>> end = time.time()
>>> execution_time = end - start
```


In [27]:
import numpy as np
import random
import time

# nparr = np.random.random((100, 100))
# pyarr = [[random.random() for _ in range(100)] for _ in range(100)]

start = time.time()
nparr = np.random.random((100, 100))
newarr = nparr*nparr
end = time.time()
execution_time = end - start
print(execution_time)
print()
# [[] for in range]
# 다른 array도 생각해보자..
start = time.time()
pyarr = [[random.random() for _ in range(100)] for _ in range(100)]
newarr = []
for i, l in enumerate(pyarr):
    newarr.append([x*pyarr[i][j] for j, x in enumerate(l)])
end = time.time()
execution_time = end - start
print(execution_time)


0.0010020732879638672

0.0025501251220703125



Python built-in list와 NumPy ndarray 중 어느 것이 더 편리한가요?

연산 시간의 차이는 어느정도 인가요?

---

**문제2 ndarray 생성과 사용**
   
ndarray를 이용해서 다음 모양의 matrix를 만들어 보세요

예시)
```
>>> my_arr
array([[0., 0., 1., 1.],
       [0., 0., 1., 1.],
       [2., 2., 3., 3.],
       [2., 2., 3., 3.]])
```

In [147]:
a = np.array([[int(i/2) for i in range(j, j+4)] for j in range(0, 8, 4) for _ in range(2)]).reshape(4,4).astype(float)
print(a)
b = np.array([[int(i/2) for i in range(j, j+4)]*2 for j in range(0, 8, 4)])
print(b)
b = b.reshape(4,4).astype(float)
print(b)

[[0. 0. 1. 1.]
 [0. 0. 1. 1.]
 [2. 2. 3. 3.]
 [2. 2. 3. 3.]]
[[0 0 1 1 0 0 1 1]
 [2 2 3 3 2 2 3 3]]
[[0. 0. 1. 1.]
 [0. 0. 1. 1.]
 [2. 2. 3. 3.]
 [2. 2. 3. 3.]]


---

**문제3 ndarray 생성과 사용**

ndarray를 이용해서 다음 모양의 matrix를 만들어 보세요

예시)
```
>>> my_arr
array([[1., 0., 0., 0., 1.],
       [0., 1., 0., 1., 0.],
       [0., 0., 2., 0., 0.],
       [0., 1., 0., 1., 0.],
       [1., 0., 0., 0., 1.]])
```


In [69]:
np.identity(5) + np.flipud(np.identity(5))

array([[1., 0., 0., 0., 1.],
       [0., 1., 0., 1., 0.],
       [0., 0., 2., 0., 0.],
       [0., 1., 0., 1., 0.],
       [1., 0., 0., 0., 1.]])

---

**문제4 ndarray 생성과 사용**

ndarray를 이용해서 다음 모양의 matrix를 만들어 보세요  

예시)

```
>>> my_arr
array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])
```



In [72]:
ndarr = np.zeros((8,8))
for i in range(4):
    ndarr += np.eye(8, 8, i*2)
    if i > 0:
        ndarr += np.eye(8, 8, i*-2)
print(ndarr)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


---

**문제5**

매 달 마다 통장의 돈이 n 배가 되는 마법의 통장이 있습니다.

이 통장에 1,000원을 넣어두었더니 12달 후에 무려 10,000,000만원이 되어있었습니다.

과연 n은 얼마였을까요?

In [141]:
np.logspace(0, 1/3, 20)
# [ np.exp(i) for i in np.linspace(np.log(1), np.log(2.15), 4) ]
# #print(np.log(0))
# # np.geomspace(1, 1/3, 30)
# # np.exp(2.15443469)
# np.log(2.15)
1000*(2.15443469**12)

b = np.geomspace(1, 10000, 12)
print(b[4]/b[3])
a = np.geomspace(1, 10000, num=13, endpoint=True)
print(a[4]/a[3])
print(a)


2.31012970008316
2.1544346900318834
[1.00000000e+00 2.15443469e+00 4.64158883e+00 1.00000000e+01
 2.15443469e+01 4.64158883e+01 1.00000000e+02 2.15443469e+02
 4.64158883e+02 1.00000000e+03 2.15443469e+03 4.64158883e+03
 1.00000000e+04]


---

**문제6**  
다음 2가지 array가 있습니다.

2가지 array는 동일한 순서대로 10명의 사람의 정보를 나타냅니다. 즉, 같은 index의 정보는 같은 사람의 정보입니다.

첫 번째 array는 각 사람의 근속 년 수를 의미합니다.

두 번째 array는 각 사람의 나이를 의미합니다.

나이가 50 이상인 직원들의 근속 년 수 총합을 구해보세요

array 예시)
```
>>> years
array([11, 18, 18,  8, 12, 17,  1,  4,  0, 14])
```
```
>>> age
array([64, 24, 36, 33, 33, 44, 39, 65, 25, 20])
```


In [75]:
totalYears = 0
years = np.array([11, 18, 18,  8, 12, 17,  1,  4,  0, 14])
ages = np.array([64, 24, 36, 33, 33, 44, 39, 65, 25, 20])
for i, age in enumerate(ages):
    if age >= 50:
       totalYears += years[i]

print(totalYears)



15


---