# Pandas Basics


**[실습 유의 사항]**

https://docs.google.com/spreadsheets/d/1LufpYknSbN7179sVPreZ-hDJ7vHaZ1l64XMZeivjySQ/edit?usp=sharing

공유한 파일에 실습 현황을 공유해 주세요. 수업 진행에 도움이 됩니다.

**수업에 필요한 모듈을 임포트하세요.** 


In [16]:
import numpy as np
import pandas as pd

**문제1**    

1) 아래의 딕셔너리`data`를 이용하여 데이터프레임`df1`를 생성하세요.   

```
data = {'A': [0, 5, 15, 20, 25, 30, 35, 40], 'B' : [16, 14, 12, 10, 8, 6, 4, 2]}
```

2) 아래의 값을 가지는 `C`와 `D` 그리고 `E` 열(column)을 `df1`에 추가하세요. 

```
C = [5, 5, 5, 5, 5, 5, 5, 5]
D = [7, 2, 2, 12, 21, 6, 12, 24]
E = ['h', 'g', 'f', 'e', 'd', 'c', 'b', 'a']
F = [1, 1, 1, 1, 1, 1, 1, 1]
```

3) 각 열(column)의 자료형을 확인하세요.  


4) 각 열(column)의 합을 구하세요.

5) 각 행(row)의 합을 구하세요. (sum 함수 사용)

6) `A`, `C`, `D`열에 인덱스가 2, 3, 4, 5인 자료를 추출하세요.  


In [17]:
df1 = pd.DataFrame({'A': [0, 5, 15, 20, 25, 30, 35, 40], 'B' : [16, 14, 12, 10, 8, 6, 4, 2]})
newData = { 'C':[5, 5, 5, 5, 5, 5, 5, 5], \
            "D":[7, 2, 2, 12, 21, 6, 12, 24], \
            "E":['h', 'g', 'f', 'e', 'd', 'c', 'b', 'a'],\
            "F": [1, 1, 1, 1, 1, 1, 1, 1]}
for k, v in newData.items():
    df1[k] = v

print(df1)

df1.info()

df1.iloc[:, 2].sum()

print()

for i, col in df1.items():
    print(col.name, ": ", col.sum())

print()

print(df1.sum(axis=1, numeric_only=True))

print(df1.loc[2:5, ['A', 'C', 'D']])
# for i, row in df1.iterrows():
#     print(i, ": ", row.sum(numeric_only=True))

    A   B  C   D  E  F
0   0  16  5   7  h  1
1   5  14  5   2  g  1
2  15  12  5   2  f  1
3  20  10  5  12  e  1
4  25   8  5  21  d  1
5  30   6  5   6  c  1
6  35   4  5  12  b  1
7  40   2  5  24  a  1
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   A       8 non-null      int64 
 1   B       8 non-null      int64 
 2   C       8 non-null      int64 
 3   D       8 non-null      int64 
 4   E       8 non-null      object
 5   F       8 non-null      int64 
dtypes: int64(5), object(1)
memory usage: 512.0+ bytes

A :  170
B :  72
C :  40
D :  86
E :  hgfedcba
F :  8

0    29
1    27
2    35
3    48
4    60
5    48
6    57
7    72
dtype: int64
    A  C   D
2  15  5   2
3  20  5  12
4  25  5  21
5  30  5   6


---

**문제2**

1) `score.txt` 파일에는 100명의 학생들의 국어, 영어, 수학, 사회, 과학 점수가 들어 있습니다.      
이 자료를 담은 데이터프레임 `df_score`를 만드세요.

2) `df_score`의 처음부터 5개의 행(row)을 확인하세요.  
참고) `head()` 메소드 이용

3) `df_score`의 마지막 10개의 행(row)을 확인하세요.  
참고) `tail()` 메소드 이용

4) 국어 점수가 80점이상인 학생들의 데이터만 추출하세요. 

5) 각 과목에서 10점이하의 값들은 `np.nan`으로 변경하세요.    
(결측치(누락된 값)를 처리하는 연습을 위해)     
참고) `np.nan` 이용 

6) 각 열에 있는 결측치의 개수는 몇 개인가요?  
참고)  `isnull()` 또는 `notnull()` 메소드를 사용하여 누락된 데이터를 확인할 수 있습니다.

7) 결측치의 개수가 20%인 이하인 열(column)들만 담은 데이터프레임`df_score_20`을 만드세요.  



---

In [18]:
a = np.array([[1, 2, 3], [4,5,6]])
a.sum(axis=1)

array([ 6, 15])

In [19]:
df_score = pd.read_csv("score.txt", skiprows=2, names=["국어", "영어", "수학", "사회", "과학"])
df_score.info()
print(df_score.head())
print(df_score.tail())

print(df_score["국어"] >= 80)

print()

print(df_score.sum(axis=0))
print(df_score.sum(axis=1))

print(df_score[(df_score["국어"] >= 80)])
df_score[df_score < 10] = np.NaN
print(df_score)


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   국어      100 non-null    int64
 1   영어      100 non-null    int64
 2   수학      100 non-null    int64
 3   사회      100 non-null    int64
 4   과학      100 non-null    int64
dtypes: int64(5)
memory usage: 4.0 KB
   국어  영어  수학  사회  과학
0  15  16  21   0  14
1  96  91  14  11  75
2  49  63  15  18  61
3  54   4  20  21   1
4  46   8   7  23   9
    국어  영어  수학  사회  과학
95  69  61  11  28  97
96  41  97  16  13   8
97   0  84  18   9  15
98  19  11  15   2  90
99   0   7  33   7  58
0     False
1      True
2     False
3     False
4     False
      ...  
95    False
96    False
97    False
98    False
99    False
Name: 국어, Length: 100, dtype: bool

국어    5364
영어    4946
수학    3580
사회    2092
과학    5102
dtype: int64
0      66
1     287
2     206
3     100
4      93
     ... 
95    266
96    175
97    126
98    137
99    10

In [24]:
# print(df_score)
aa = df_score.isnull().sum()
print(aa)
# print(type(aa))

# print()

# df_score.count() 는 nan이 빠진 수.
# print("count = ", df_score.count())
# print("len = ". len(df_score.index))

# print(type(df_score >= 80))
df_score_20 = (df_score.loc[:, df_score.count()/len(df_score.index)>=0.8])
print(df_score_20)


국어     5
영어    11
수학    12
사회    26
과학    11
dtype: int64
      국어    영어    수학    과학
0   15.0  16.0  21.0  14.0
1   96.0  91.0  14.0  75.0
2   49.0  63.0  15.0  61.0
3   54.0   NaN  20.0   NaN
4   46.0   NaN   NaN   NaN
..   ...   ...   ...   ...
95  69.0  61.0  11.0  97.0
96  41.0  97.0  16.0   NaN
97   NaN  84.0  18.0  15.0
98  19.0  11.0  15.0  90.0
99   NaN   NaN  33.0  58.0

[100 rows x 4 columns]


**문제3**

1) `covid19_seoul.csv` 파일을 읽어 데이터프레임 `df_covid`를 만드세요.

참고) 파일이 제대로 열리지 않는다면, `encoding = 'cp949'` 또는 `'euk-kr'`로 지정

2) `df_covid`의 처음 5개와 끝 5개의 행을 확인하세요.

3) `df_covid`의 열(column)에는 어떠한 것이 있나요? 열의 개수는 몇 개인가요?

4) `df_covid`에는 몇 개의 관측치가 있나요?

5) 가장 많은 확진자가 나온 날은 언제인가요? 그때의 확진자 수는 몇 명인가요? (loop를 사용하여 풀 수 있습니다.)

---

In [28]:
df_covid = pd.read_csv("covid19_seoul.csv", encoding="cp949")
# print(df_covid)
# df_covid.head()
# df_covid.tail()
df_covid.info()
print(df_covid.columns)
print(len(df_covid.columns))
print(len(df_covid.index))

df_covid_g = df_covid.groupby('확진일').size()

maxv = 0
key = None
for k,v in dict(df_covid_g).items():
    tmpmax = max(maxv, v)
    if  maxv != tmpmax:
        maxv = tmpmax
        key = k
print(key)

# df_covid.groupby('확진일').size()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 136376 entries, 0 to 136375
Data columns (total 14 columns):
 #   Column  Non-Null Count   Dtype  
---  ------  --------------   -----  
 0   연번      136376 non-null  int64  
 1   확진일     136376 non-null  object 
 2   환자번호    0 non-null       float64
 3   국적      0 non-null       float64
 4   환자정보    0 non-null       float64
 5   지역      136376 non-null  object 
 6   여행력     1933 non-null    object 
 7   접촉력     136376 non-null  object 
 8   조치사항    0 non-null       float64
 9   상태      136376 non-null  object 
 10  이동경로    30000 non-null   object 
 11  등록일     136376 non-null  object 
 12  수정일     136376 non-null  object 
 13  노출여부    136376 non-null  object 
dtypes: float64(4), int64(1), object(9)
memory usage: 14.6+ MB
Index(['연번', '확진일', '환자번호', '국적', '환자정보', '지역', '여행력', '접촉력', '조치사항', '상태',
       '이동경로', '등록일', '수정일', '노출여부'],
      dtype='object')
14
136376
2021-11-16


C:\Users\edu\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3444: DtypeWarning: Columns (10) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)


확진일
2020-01-24       1
2020-01-30       3
2020-01-31       3
2020-02-02       1
2020-02-05       2
              ... 
2021-11-13     978
2021-11-14     858
2021-11-15     846
2021-11-16    1436
2021-11-17    1429
Length: 632, dtype: int64

**문제4**   
dataframe의 index를 'Manufacturer_Model_Type' 설정하세요.
null value인 경우 'missing'으로 바꾸고, 필요없는 columns ( manufacturer, model, type)을 제거하세요.

In [ ]:
# 결과 예시

  Manufacturer    Model     Type  ...  Weight   Origin           Make
0        Acura  Integra    Small  ...  2705.0  non-USA  Acura Integra
1          NaN   Legend  Midsize  ...  3560.0  non-USA   Acura Legend
2         Audi       90  Compact  ...  3375.0  non-USA        Audi 90
3         Audi      100  Midsize  ...  3405.0  non-USA       Audi 100
4          BMW     535i  Midsize  ...  3640.0  non-USA       BMW 535i

[5 rows x 27 columns]


In [149]:
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

In [152]:
df.info()
df2 = df.fillna('missing', inplace=False).drop(['Manufacturer', 'Model', 'Type'], axis='columns')
print(df2)
df2.drop()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 93 entries, 0 to 92
Data columns (total 27 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   Manufacturer        89 non-null     object 
 1   Model               92 non-null     object 
 2   Type                90 non-null     object 
 3   Min.Price           86 non-null     float64
 4   Price               91 non-null     float64
 5   Max.Price           88 non-null     float64
 6   MPG.city            84 non-null     float64
 7   MPG.highway         91 non-null     float64
 8   AirBags             87 non-null     object 
 9   DriveTrain          86 non-null     object 
 10  Cylinders           88 non-null     object 
 11  EngineSize          91 non-null     float64
 12  Horsepower          86 non-null     float64
 13  RPM                 90 non-null     float64
 14  Rev.per.mile        87 non-null     float64
 15  Man.trans.avail     88 non-null     object 
 16  Fuel.tank.

---

## Numpy 추가 문제


**문제5**    

Numpy를 이용하여 입력에 대하여 좌우상하 'pad'만큼 '0'으로 padding하는 함수 zero_padding(arr, padding)을 구현하세요.    
arr는 2D array(정사각행렬일 필요 없음), pad는 좌우상하 동일합니다.    
(np.pad 함수를 쓰지말 것, 해당 함수를 구현하는 것이 목표입니다.)      
hint: numpy slicing



```
>>> arr = np.arange(1,26).reshape((5,5))
>>> padding = 2
>>> zero_padding(arr, padding)
[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  1.  2.  3.  4.  5.  0.  0.]
 [ 0.  0.  6.  7.  8.  9. 10.  0.  0.]
 [ 0.  0. 11. 12. 13. 14. 15.  0.  0.]
 [ 0.  0. 16. 17. 18. 19. 20.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.]]

```

In [14]:
import numpy as np
arr = np.arange(1,26).reshape((5,5))
padding = 2
def zero_padding(arr,pad):
    result = np.zeros((arr.shape[0]+(padding*2), arr.shape[1]+(padding*2)))
    #   zero_arr[2, 2] = 1
    result[padding:padding+arr.shape[0], 2:padding+arr.shape[1]] = arr
    return result # np.array 반환
zero_padding(arr, padding)

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  2.,  3.,  4.,  5.,  0.,  0.],
       [ 0.,  0.,  6.,  7.,  8.,  9., 10.,  0.,  0.],
       [ 0.,  0., 11., 12., 13., 14., 15.,  0.,  0.],
       [ 0.,  0., 16., 17., 18., 19., 20.,  0.,  0.],
       [ 0.,  0., 21., 22., 23., 24., 25.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [15]:
arr2 = np.ones((2,3,4,5))
# print(arr2)
arr2.sum(axis=1)

[[[[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]]


 [[[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]]]


array([[[3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.]],

       [[3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.]]])

---

**문제6**  
'ratings.csv'파일을 읽어와 datafame을 인자로 받고, 각 영화별 평점 평균을 구하는 함수 get_ratings_numpy()를 구현하세요. 
넘파이를 사용하여 구현하세요.   
hint: np.where

```
>>> get_ratings_numpy(df)
1.0: 3.9209302325581397,
2.0: 3.4318181818181817,
3.0: 3.2596153846153846,
4.0: 2.357142857142857,
... 
```

In [35]:
import numpy as np
import pandas as pd

ratings_path = 'ratings.csv'
ratings = pd.read_csv(ratings_path)

#ratings.info()
def get_ratings_numpy(df):
    arr = np.array(df, dtype=float)      # Hint
    ratingIdx = df.columns.get_loc("rating")
    movieIdIdx = df.columns.get_loc("movieId")
    ratings = {} # key: 영화 id, value: 평균 평점
    print(np.where(arr[:, 1])
    print(np.mean(arr[np.where(arr[:, 1] == 2), 2]))
    #print(np.unique(arr[:, 1]))
    for movieId in np.unique(arr[:, 1]):
        ratings[movieId]  = np.mean(arr[np.where(arr[:, 1] == movieId), 2])
    return ratings 
get_ratings_numpy(ratings)

SyntaxError: closing parenthesis ']' does not match opening parenthesis '(' (Temp/ipykernel_14028/3020150961.py, line 13)

In [8]:
df = pd.read_csv("seoul2020.txt", sep="\t", thousands=",")
df.info()
df.head()
df.tail()
df.set_index(["기간", "자치구"])

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80 entries, 0 to 79
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   기간        80 non-null     object
 1   자치구       80 non-null     object
 2   세대        80 non-null     object
 3   인구        80 non-null     object
 4   인구.1      80 non-null     object
 5   인구.2      80 non-null     object
 6   인구.3      80 non-null     object
 7   인구.4      80 non-null     object
 8   인구.5      80 non-null     object
 9   인구.6      80 non-null     object
 10  인구.7      80 non-null     object
 11  인구.8      80 non-null     object
 12  세대당인구     80 non-null     object
 13  65세이상고령자  80 non-null     object
dtypes: object(14)
memory usage: 8.9+ KB


세대          인구       인구.1       인구.2       인구.3  \
기간       자치구                                                           
기간       자치구         세대          합계         합계         합계        한국인   
         자치구         세대           계         남자         여자          계   
2020.1/4 합계   4,354,006  10,013,781  4,874,995  5,138,786  9,733,655   
         종로구     74,151     161,984     78,271     83,713    151,217   
         중구      63,045     136,469     66,769     69,700    126,175   
...                 ...         ...        ...        ...        ...   
2020.3/4 관악구    275,248     514,555    257,638    256,917    498,574   
         서초구    173,483     429,995    205,671    224,324    426,009   
         강남구    234,021     544,085    260,358    283,727    539,235   
         송파구    281,417     676,673    326,602    350,071    670,331   
         강동구    194,602     462,275    227,346    234,929    458,058   

                   인구.4       인구.5     인구.6     인구.7     인구.8  세대당인구  \
기간       자치구                                                           
기간       자치구        한국인        한국인    등록외국인    등록외국인    등록외국인  세대당인구   
         자치구         남자         여자        계       남자       여자  세대당인구   
2020.1/4 합계   4,742,217  4,991,438  280,126  132,778  147,348   2.24   
         종로구     73,704     77,513   10,767    4,567    6,200   2.04   
         중구      61,839     64,336   10,294    4,930    5,364      2   
...                 ...        ...      ...      ...      ...    ...   
2020.3/4 관악구    250,084    248,490   15,981    7,554    8,427   1.81   
         서초구    203,686    222,323    3,986    1,985    2,001   2.46   
         강남구    257,961    281,274    4,850    2,397    2,453    2.3   
         송파구    323,646    346,685    6,342    2,956    3,386   2.38   
         강동구    225,396    232,662    4,217    1,950    2,267   2.35   

               65세이상고령자  
기간       자치구             
기간       자치구   65세이상고령자  
         자치구   65세이상고령자  
2020.1/4 합계   1,518,239  
         종로구     28,073  
         중구      23,794  
...                 ...  
2020.3/4 관악구     78,206  
         서초구     59,495  
         강남구     73,942  
         송파구     92,149  
         강동구     68,798  

[80 rows x 12 columns]